baseURL: https://flying-spoiler.github.io/portfolio.com/
languageCode: ja-jp
title: ひこうきメモ
theme: vanilla-bootstrap-hugo-theme
googleAnalytics: UA-123456789-1

publishDir : "docs"

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: home
    pre: home
    url: /
    weight: 1
  - name: 記事
    pre: edit
    url: /post/
    weight: 2
  - name: 記事(タグ別)
    pre: tag
    url: /tags/
    weight: 3

params:
  includeBootstrapJs: false
  showActiveNav: true
  containerMaxWidth: 700px
  dateFormat: Jan 2, 2006
  homeText: 好きなことを好きなだけ書いたサイトへようこそ。
  footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: false
  katex: true

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
